### ISSUE TITLE
hello 5-12 yr old

### ISSUE THREAD

**Issue by VladatBoss** [FuckingToasters/hacking_tool_collection#1]
I can see the 9 year old searching for hacking tools ong💀

**Comment by FuckingToasters** [comment]
> I can see the 9 year old searching for hacking tools ong💀

Yes that is true however users should really try to anonymize them. The Giverment is no Children's playground and will probably come for them. Especially because the Tool is legit and use a zero day exploit that is really difficult to patch. I recommend that the use of the program is not used for bad deeds but to learn Python and hack your own goverment :) However, I can not control it either.

**Comment by VladatBoss** [comment]
> 

I think it was very irresponsible for the creator of this not to give a warning on top of the code, I hope he does some day.

**Comment by VladatBoss** [comment]
> to

oh you are the creator, please do it there are some people who don't know what this is and will use it irresponsibly without reading the markdown

**Comment by FuckingToasters** [comment]
> > to
> 
> oh you are the creator, please do it there are some people who don't know what this is and will use it irresponsibly without reading the markdown

done.
